name: kampus_guvenlik
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  image_picker: ^1.0.4

  # Firebase Paketleri (Sürümleri belirtmek çakışmaları önler)
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.0

  provider: ^6.1.2
  url_launcher: ^6.3.2
  gal: ^2.3.2
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Projenin SDK sürümüne uygun olan budur
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ataunikampus1.jpeg"